### ISSUE TITLE
1.16.1兼容性异常

### ISSUE THREAD

**Issue by nenglizuida** [Zaohon/ServerChat#2]
能够使用，但是会有一大串的报错
https://www.mcbbs.net/forum.php?mod=redirect&goto=findpost&ptid=704339&pid=18716654

**Comment by Zaohon** [comment]
暂时还没更新1.16.1.下个版本将会支持

**Comment by CuteLittleSky** [comment]
> 暂时还没更新1.16.1.下个版本将会支持

1.18不能用了..

**Comment by Zaohon** [comment]
新版本更新了，1.18可以了

**Comment by CuteLittleSky** [comment]
> 新版本更新了，1.18可以了

考虑一下兼容velocity?
https://papermc.io/downloads#Velocity
