### ISSUE TITLE
1.8.0聊天会报错，如下图

### ISSUE THREAD

**Issue by Baikele** [Zaohon/ServerChat#3]
![GitHub Logo](https://img1.baikele.online/2020/11/30/75e83c64e8050.jpg)

1.7.9版本papi显示不正常，如4月份那个老哥提交的内容一致

**Comment by Zaohon** [comment]
这个报错是什么时候会出现

**Comment by Baikele** [comment]
> 这个报错是什么时候会出现

聊天的时候，发送信息的时候触发

**Comment by Baikele** [comment]
> 这个报错是什么时候会出现

如果可以，可以在mcbbs私信聊一下么？
